/* eslint-disable */
export const SET_SAVE_STATUS = "SET_SAVE_STATUS";
export const SAVE_STATUS_SAVING = "SAVE_STATUS_SAVING";
export const SAVE_STATUS_DONE = "SAVE_STATUS_DONE";

export const CHANGE_ORGANIZATION_LIST = 'CHANGE_ORGANIZATION_LIST';
export const GET_ORGANIZATIONS= 'GET_ORGANIZATIONS';
export const SAVE_ORGANIZATION = 'SAVE_ORGANIZATION';

export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const SET_ACTIVE_ORGANIZATION = 'SET_ACTIVE_ORGANIZATION'
export const GET_ORGANIZATION_BY_ID = 'GET_ORGANIZATION_BY_ID'
export const SET_ORGANIZATION_PROP = "SET_ORGANIZATION_PROP";
export const NEW_ORGANIZATION = "NEW_ORGANIZATION";
export const CREATE_NEW_ORGANIZATION = 'CREATE_NEW_ORGANIZATION';

export const SET_ACTIVE_USER = "SET_ACTIVE_USER";
export const SET_USER_PROP = "SET_USER_PROP";
export const SAVE_USER = 'SAVE_USER';

export const SET_CHANNEL_PROP = "SET_CHANNEL_PROP";
export const SAVE_CHANNEL = "SAVE_CHANNEL";
export const DELETE_CHANNEL = "DELETE_CHANNEL";

export const SET_CHANNELGROUP_PROP = "SET_CHANNELGROUP_PROP";
export const SAVE_CHANNELGROUP = "SAVE_CHANNELGROUP";
export const DELETE_CHANNELGROUP = "DELETE_CHANNELGROUP";

export const NEW_CHANNEL = "NEW_CHANNEL";
export const NEW_DEVICEGROUP = "NEW_DEVICEGROUP";
export const NEW_USER = "NEW_USER";
export const NEW_CHANNELGROUP = 'NEW_CHANNELGROUP';

export const LOGIN_AS_USER = 'LOGIN_AS_USER';

export const GET_SMS_BALANCE = "GET_SMS_BALANCE";
export const SET_SMS_BALANCE = "SET_SMS_BALANCE";
export const TOP_UP_SMS = "TOP_UP_SMS"

export const SET_LOAD_STATUS = "SET_LOAD_STATUS";
