var constants = {
  GO_TO_NEXT_QUESTION: 'GO_TO_NEXT_QUESTION',
  GO_TO_QUESTION: 'GO_TO_QUESTION',
  GO_TO_END: 'GO_TO_END',
  NEW_FBEVENT: 'NEW_FBEVENT',
  ACTIVE_TRANSLATION_CHANGE: 'ACTIVE_TRANSLATION_CHANGE',
  CLASS_PREFIX: 'feedback-plugin',
  OPEN_TIMEOUT: 8 * 1000,
  END_TIMEOUT: 5 * 1000
};

module.exports = constants;
