module.exports = {
  FILE_EXPORTS: {
    CSV: "FILE_EXPORTS_CSV",
    PDF: "FILE_EXPORTS_PDF",
    XLSX: "FILE_EXPORTS_XLSX",
    ALL: "FILE_EXPORTS_ALL"
  },
  SURVEY_LOGIC: "SURVEY_LOGIC",
  SURVEY_APPEARANCE_CUSTOMIZATION: "SURVEY_APPEARANCE_CUSTOMIZATION",
  NOTIFICATIONS: {
    TO_ORGANIZATION_USERS: "NOTIFICATIONS_TO_ORGANIZATION_USERS",
    TO_ALL_EMAILS: "NOTIFICATIONS_TO_ALL_EMAILS"
  },
  ORGANIZATION_LOGO: "ORGANIZATION_LOGO",
  FEEDBACK_INBOX: "FEEDBACK_INBOX",
  REST_API: "REST_API",
  SMS_MESSAGES: "SMS_MESSAGES",
  CHANNEL_CREATION: "CHANNEL_CREATION",
  UPSELL_MODULE: "UPSELL_MODULE"
};
