export const SET_PHASE = "SET_PHASE";
export const SET_ORGANIZATION_PROP = "SET_ORGANIZATION_PROP";
export const SET_LOADING_STATE = "SET_LOADING_STATE";
export const POST_SIGNUP_SUCCESS = "POST_SIGNUP_SUCCESS";
export const SET_SIGNUP_INFO = "SET_SIGNUP_INFO";

export const POST_SIGNUP = "POST_SIGNUP";
export const GET_UNIQUE_LINK = "GET_UNIQUE_LINK";
export const GET_SIGNUP_INFO = "GET_SIGNUP_INFO";

export const POST_POPUP = "POST_POPUP";
export const POST_POPUP_SUCCESS = "POST_POPUP_SUCCESS"
