export const PING_LOGIN = "PING_LOGIN";
export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const SET_FORWARD_TO = "SET_FORWARD_TO";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const POST_RESET_LINK = "POST_RESET_LINK";
export const SET_UI_MESSAGE = "SET_UI_MESSAGE";
export const SHOW_UI_MESSAGE = "SHOW_UI_MESSAGE";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";

export const GET_ORGANIZATION_CHARGES = "GET_ORGANIZATION_CHARGES";
export const SET_ORGANIZATION_CHARGES = "SET_ORGANIZATION_CHARGES";

export const GET_REFERRAL_STATUS = "GET_REFERRAL_STATUS";
export const SET_REFERRAL_STATUS = "SET_REFERRAL_STATUS";

export const SET_PRINT_INVOICE = "SET_PRINT_INVOICE";
